[package]
name = "rep-indy-hash"
version = "0.1.1"
description = "Representationally Independent Hash for motoko"
repository = "https://github.com/skilesare/RepIndyHash.mo"
keywords = [ "hash", "ICRC3" ]
license = "MIT"

[dependencies]
base = "https://github.com/dfinity/motoko-base#moc-0.10.0@a15ca7cd26335505e103288654f480a44463d844"
vector = "0.2.0"
sha2 = "0.0.4"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.4.1@2711d18727e954b11afc0d37945608512b5fbce2"
array = "https://github.com/aviate-labs/array.mo#v0.2.1@89bb25b7f24ab31082ee3d843d720404eb1d0304"
motoko_numbers = "https://github.com/edjCase/motoko_numbers#v1.1.0@773953141f976ccdfc2e6a2c451b841a53bb39a0"